/* De proyectos */
const FORM_PROJECT = 'FORM_PROJECT';
const GET_PROJECTS = 'GET_PROJECTS';
const ADD_PROJECT = 'ADD_PROJECT';
const VALIDATE_FORM = 'VALIDATE_FORM';
const CURRENT_PROJECT = 'CURRENT_PROJECT';
const REMOVE_PROJECT = 'REMOVE_PROJECT';
const PROJECT_ERROR = 'PROJECT_ERROR';
const RESET_PROJECT_STATE = 'RESET_PROJECT_STATE';

/* De tareas */
const PROJECT_TASKS = 'PROJECT_TASKS';
const ADD_TASK = 'ADD_TASK';
const VALIDATE_TASK_FORM = 'VALIDATE_TASK_FORM';
const REMOVE_TASK = 'REMOVE_TASK';
const REMOVE_PROJECT_TASKS = 'REMOVE_PROJECT_TASKS';
const EDIT_TASK = 'EDIT_TASK';
const CURRENT_TASK = 'CURRENT_TASK';
const RESET_TASKS_STATE = 'RESET_TASKS_STATE';

/* De alertas */
const SHOW_ALERT = 'SHOW_ALERT';
const HIDE_ALERT = 'HIDE_ALERT'

/* De auth */
const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const GET_USER = 'GET_USER';
const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT = 'LOGOUT';

export {
    FORM_PROJECT,
    GET_PROJECTS,
    ADD_PROJECT,
    VALIDATE_FORM,
    CURRENT_PROJECT,
    REMOVE_PROJECT,
    PROJECT_ERROR,
    RESET_PROJECT_STATE,

    PROJECT_TASKS,
    ADD_TASK,
    VALIDATE_TASK_FORM,
    REMOVE_TASK,
    REMOVE_PROJECT_TASKS,
    EDIT_TASK,
    CURRENT_TASK,
    RESET_TASKS_STATE,

    SHOW_ALERT,
    HIDE_ALERT,

    SIGNUP_SUCCESSFUL,
    SIGNUP_ERROR,
    GET_USER,
    LOGIN_SUCCESSFUL,
    LOGIN_ERROR,
    LOGOUT
};